{{ range .Values.realms }}
{{ $realmName := .name }}
{{ range .clients }}
{{ $suffix := lower (printf "%s-%s" $realmName .name) }}
{{- $secretName := include "common.secrets.name" (dict "existingSecret" "" "defaultNameSuffix" $suffix "context" $) }}
{{- $password := include "radar-keycloak.secret.value" (dict "secret" $secretName "key" "clientSecret" "context" $) | default (randAlphaNum 65) }}
{{ $client := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  clientId: {{ $client.clientId | b64enc | quote }}
  clientSecret: {{ $password | b64enc | quote }}
---
{{- if $.Values.metrics.enabled }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: monitoring
type: Opaque
data:
  clientId: {{ $client.name | b64enc | quote }}
  clientSecret: {{ $password | b64enc | quote }}
{{- end }}

{{- end }}
{{- end }}
