{{- range .Values.realms }}
{{- $realmName := .name }}
{{- range .clientScopes }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: {{ $realmName }}-{{ include "radar-keycloak.name.clean" .name }}
spec:
  name: {{ .name | quote }}
  realmRef:
    name: {{ include "common.names.fullname" $ }}-{{ $realmName }}
    kind: KeycloakRealm
  protocol: openid-connect
  description: {{ .description | quote }}
  attributes:
    {{- range .attributes }}
    {{ .name }}: {{ .value | quote }}
    {{- end }}
  {{- if .protocolMapper }}
  protocolMappers:
    - name: {{ index "claim.name" .config | quote }}
      protocol: openid-connect
      protocolMapper: {{ .protocolMapper }}
      config:
        {{ .config | toYaml | indent 8 | trim }}
  {{- end }}
---
{{- end }}
{{- end }}
