{{- $adminSecretName := include "common.secrets.name" (dict "existingSecret" "" "defaultNameSuffix" "admin" "context" $) }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: radar-keycloak
spec:
  {{- with .Values.keycloak.additionalOptions }}
  additionalOptions:
    env:
      {{ . | toYaml | nindent 6 }}
  {{- end }}
  instances: {{ .Values.replicaCount }}
  ingress:
    # We use our own Ingress definition that has more flexibility
    enabled: false
  hostname:
    hostname: {{ .Values.advertised_protocol }}://keycloak.{{ .Values.serverName }}
    admin: {{ .Values.advertised_protocol }}://keycloak.{{ .Values.serverName }}
{{/*    strict: false*/}}
  image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global "chart" .Chart ) }}
  # By default, operator considers docker images to be optimized (built). If we would like the image to build before running,
  # set to 'false'.
  startOptimized: false
  http:
    httpEnabled: true
    labels:
      # Needed for selection of the ServiceMonitor by Prometheus.
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}
  bootstrapAdmin:
    user:
      secret: {{ $adminSecretName }}
  db:
    vendor: postgres
    usernameSecret:
      name: {{ .Values.database.usernameSecret.name }}
      key: {{ .Values.database.usernameSecret.key }}
    passwordSecret:
      name: {{ .Values.database.passwordSecret.name }}
      key: {{ .Values.database.passwordSecret.key }}
    url: {{ .Values.database.url }}
    poolInitialSize: 1
    poolMinSize: 2
    poolMaxSize: 3
  features:
    enabled:
      - docker
      - authorization
      - admin
      - admin-fine-grained-authz:v2
      - scripts
    disabled:
      - step-up-authentication
  additionalOptions:
    - name: metrics-enabled
      value: {{ .Values.metrics.enabled | default false | quote }}
    - name: event-metrics-user-enabled
      value: {{ .Values.metrics.enabled | default false | quote }}
    - name: http-metrics-histograms-enabled
      value: "true"

