## nginx configuration
## Ref: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/index.md
##

controller:
  allowSnippetAnnotations: true
  # -- Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    ssl-redirect: "true"
    server-tokens: "false"
    annotations-risk-level: "Critical"
  addHeaders:
    X-Frame-Options: Deny
    X-Xss-Protection: 1; mode=block
    X-Content-Type-Options: nosniff

  ingressClassResource:
    # -- If true, Ingresses without `ingressClassName` get assigned to this IngressClass on creation.
    # Ingress creation gets rejected if there are multiple default IngressClasses.
    # Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
    default: true

  watchIngressWithoutClass: true

  ## Define requests resources to avoid probe issues due to CPU utilization in busy nodes
  ## ref: https://github.com/kubernetes/ingress-nginx/issues/4735#issuecomment-551204903
  ## Ideally, there should be no limits.
  ## https://engineering.indeedblog.com/blog/2019/12/cpu-throttling-regression-fix/
  resources:
    requests:
      cpu: 100m
      memory: 90Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  service:
    ipFamilyPolicy: "PreferDualStack"
