{{- $secretname :=  include "common.secrets.name" (dict "existingSecret" .Values.existingSecret "defaultNameSuffix" "root-password" "context" $) }}
{{- $password := include "cbio-keycloak-mariadb.secret.value" (dict "secret" $secretname "key" "password" "context" $) | default (randAlphaNum 65) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretname }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ $password | b64enc | quote }}