apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-cbioportal-uri
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jdbc-uri: {{ .Values.uri | default (printf "jdbc:mysql://%s:%s/%s" (include "common.names.fullname" .) (.Values.port | default "3306") "cbioportal") | b64enc | quote }}