{{ range .Values.realms }}
{{ $realmName := .name }}
{{ range .clients }}
{{ $secretSuffix := printf "%s-%s" $realmName .name }}
{{ $secretName := include "common.secrets.name" (dict "existingSecret" "" "defaultNameSuffix" $secretSuffix "context" $) }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ .name }}
spec:
  realmRef:
    name: {{ include "common.names.fullname" $ }}-{{ $realmName }}
    kind: KeycloakRealm
  advancedProtocolMappers: true
  clientId: {{ .clientId }}
  secret: ${{ $secretName }}:clientSecret
  directAccess: true
  webUrl: {{ tpl .webUrl $ | quote }}
  homeUrl: "/"
  {{ if .defaultClientScopes }}
  defaultClientScopes:
    {{ .defaultClientScopes | toYaml |  nindent 4 | trim }}
  {{- end }}
  redirectUris:
    {{ range .redirectUris }}
    - {{ tpl . $ | quote }}
    {{ end }}
  {{/*  See: https://stackoverflow.com/questions/79533407/how-to-restrict-user-login-to-specific-clients-in-keycloak-based-on-attributes*/}}
  {{ if .clientSpecificLoginRole }}
  authorizationServicesEnabled: true
  serviceAccount:
    enabled: true
  authorization:
    scopes:
      - login
    policies:
      - name: access-policy
        type: role
        decisionStrategy: AFFIRMATIVE
        logic: POSITIVE
        description: "Access policy for user login"
        rolePolicy:
          roles:
            - name: {{ .name }}-login
              required: false
    permissions:
      - name: scope-permission
        type: scope
        logic: POSITIVE
        description: "Scope permission for user login"
        decisionStrategy: CONSENSUS
        policies:
          - access-policy
        scopes:
          - login
    {{- end }}
---
{{- end }}
{{- end }}
