apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: keycloak-rw
spec:
  mariaDbRef:
    name: cbio-keycloak-mariadb
  passwordSecretKeyRef:
    {{- $secretname :=  include "common.secrets.name" (dict "existingSecret" .Values.existingSecret "defaultNameSuffix" "mariadb-user" "context" $) }}
    name: {{ $secretname }}
    key: password
  maxUserConnections: 10