{{- $username := "admin" }}
{{- $secretname := include "common.secrets.name" (dict "existingSecret" .Values.existingSecret "defaultNameSuffix" "admin" "context" $) }}
{{- $password := include "cbio-keycloak.secret.value" (dict "secret" $secretname "key" "password" "context" $) | default (randAlphaNum 65) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretname }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretname }}
  namespace: {{ .Values.operator.namespace | default "operator" }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
