{{- if .Values.email.enabled }}
{{- $_ := required "Email is enabled and value 'email.smtp.username' is not set. Disable email or define this value." .Values.email.smtp.username }}
{{- $_ := required "Email is enabled and value 'email.smtp.password' is not set. Disable email or define this value." .Values.email.smtp.password }}
{{- $secretname :=  include "common.secrets.name" (dict "existingSecret" .Values.existingSecret "defaultNameSuffix" "smtp-server" "context" $) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretname }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.email.smtp.username | b64enc | quote }}
  password: {{ .Values.email.smtp.password | b64enc | quote }}
{{- end }}