name: Update versions.md

on:
  push:
    branches:
      - main

jobs:
  update_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup-helmfile
        uses: mamezou-tech/setup-helmfile@v2.1.0
        with:
          install-helm-plugins: no
          install-kubectl: no
          helmfile-version: 0.67.0
          helm-version: v3.17.3

      - name: Update versions.md
        run: bin/version_scan

      - name: Commit and push if versions.md changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update versions.md" || exit 0
          git push